# Generated by Django 4.2.14 on 2024-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
