# Generated by Django 4.2.14 on 2024-09-11 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('rank', models.CharField(default='Unranked', max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('isTwoFA', models.BooleanField(default=False)),
                ('otpTwoFA', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('userStatus', models.CharField(max_length=255)),
                ('Blocked', models.JSONField(blank=True, default=list)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('userStatsId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WePongAuth.stats')),
            ],
        ),
        migrations.AddField(
            model_name='stats',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WePongAuth.user'),
        ),
    ]
